### ISSUE TITLE
Investigate using assumptions for babel-preset

### ISSUE THREAD

**Issue by vsumner** [Shopify/web-configs#246]
## Overview

See @BPScott comment [here](https://github.com/Shopify/web-configs/pull/245#issuecomment-832930581).

**Comment by BPScott** [comment]
https://babeljs.io/docs/en/babel-plugin-proposal-private-methods#options docs have been improved!

it suggests instead of using the `loose` option:

> ⚠️ Consider migrating to the top level `privateFieldsAsProperties` assumption.

This should allow us to remove explicitly setting the loose option on multiple plugins, and possibly removing the usage of those plugins entirely if they are already enabled as part of preset-env
