### ISSUE TITLE
Change NodeJS versions on GitHub actions to 16 and 18

### ISSUE THREAD

**Issue by alex-page** [Shopify/web-configs#361]
NodeJS 14 is EOL and should be replaced with the new versions.

**Comment by BPScott** [comment]
No it isn't. https://github.com/nodejs/Release suggest that the node 14 EOL date is 2023-04-30 - 4 months away. It's also worth noting that the node 16 EOL date has been brought forward to 2023-09-11 rather than in 2024-04, so rather than have to do two breaking changes within 6 months I'd rather just wait till September and drop 14 and 16 support at the same time.


We currently claim to support node 14. I am not comfortable claiming we support a node version but do not run tests against it on CI - any major version we support should be tested on CI pipeline. Dropping support for a node version is a major release. Given that we don't have any other rational for performing a major release, doing one just to chase the latest node version seems like it busywork for both the maintainers of web-configs, and anybody who consumes these packages as they'll need to do a version bump. 

Until a version of node is EOL and we have a stronger need for performing major version bumps then I am against dropping node versions for the sake of it.

---

All that said, adding node 18 to our CI is probably a good idea

**Comment by BPScott** [comment]
Getting ahead of the curve is a great plan for apps, where there are no knock-on effects to being up to date. For libraries though I think it's better to lag behind the curve in order to ensure that the widest amount of people can use the library, and ensure you're not forcing apps that consume your package to update.
